name: DeployCV

on: 
  push:
    branches: 
      - master

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: EdricChan03/action-build-deploy-ghpages@v2.2.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gh_pages_token: ${{ secrets.GITHUB_TOKEN }}

